export interface NameOfAllah {
  id: number;
  arabic: string;
  transliteration: string;
  translation: string;
  meaning: string;
}

export const namesOfAllah: NameOfAllah[] = [
  { id: 1, arabic: 'الرَّحْمَٰنُ', transliteration: 'Ar-Rahman', translation: 'The Most Gracious', meaning: 'The Beneficent, The One who has plenty of mercy for the believers and the blasphemers in this world and especially for the believers in the hereafter.' },
  { id: 2, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Raheem', translation: 'The Most Merciful', meaning: 'The Merciful, The One who has plenty of mercy for the believers.' },
  { id: 3, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', translation: 'The King', meaning: 'The Sovereign Lord, The One with the complete Dominion, the One Whose Dominion is clear from imperfection.' },
  { id: 4, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', translation: 'The Holy', meaning: 'The One who is pure from any imperfection, clear from children and adversaries.' },
  { id: 5, arabic: 'السَّلَامُ', transliteration: 'As-Salam', translation: 'The Source of Peace', meaning: 'The One who is free from every imperfection.' },
  { id: 6, arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu\'min', translation: 'The Guardian of Faith', meaning: 'The One who witnessed for Himself that no one is God but Him. And He witnessed for His believers that they are truthful in their belief that no one is God but Him.' },
  { id: 7, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', translation: 'The Protector', meaning: 'The One who witnesses the saying and deeds of His creatures.' },
  { id: 8, arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', translation: 'The Mighty', meaning: 'The Strong, The Defeater who is not defeated.' },
  { id: 9, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', translation: 'The Compeller', meaning: 'The One that nothing happens in His Dominion except that which He willed.' },
  { id: 10, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', translation: 'The Majestic', meaning: 'The One who is clear from the attributes of the creatures and from resembling them.' },
  { id: 11, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', translation: 'The Creator', meaning: 'The One who brings everything from non-existence to existence.' },
  { id: 12, arabic: 'الْبَارِئُ', transliteration: 'Al-Bari', translation: 'The Evolver', meaning: 'The Maker, The Creator who has the Power to turn the entities.' },
  { id: 13, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', translation: 'The Fashioner', meaning: 'The One who forms His creatures in different pictures.' },
  { id: 14, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', translation: 'The Great Forgiver', meaning: 'The Forgiver, The One who forgives the sins of His slaves time and time again.' },
  { id: 15, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', translation: 'The Subduer', meaning: 'The Dominant, The One who has the perfect Power and is not unable over anything.' },
  { id: 16, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', translation: 'The Bestower', meaning: 'The One who is Generous in giving plenty without any return.' },
  { id: 17, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', translation: 'The Provider', meaning: 'The Sustainer, The Provider.' },
  { id: 18, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', translation: 'The Opener', meaning: 'The Opener, The Reliever, The Judge, The One who opens for His slaves the closed worldly and religious matters.' },
  { id: 19, arabic: 'الْعَلِيمُ', transliteration: 'Al-Alim', translation: 'The All-Knowing', meaning: 'The Knowledgeable, The One nothing is absent from His knowledge.' },
  { id: 20, arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', translation: 'The Constrictor', meaning: 'The Constrictor, The Retainer, The Withholder, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy.' },
  { id: 21, arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', translation: 'The Expander', meaning: 'The Enlarger, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy.' },
  { id: 22, arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', translation: 'The Abaser', meaning: 'The Abaser, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment.' },
  { id: 23, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi', translation: 'The Exalter', meaning: 'The Exalter, The Elevator, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment.' },
  { id: 24, arabic: 'الْمُعِزُّ', transliteration: 'Al-Mu\'izz', translation: 'The Honorer', meaning: 'He gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem.' },
  { id: 25, arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', translation: 'The Dishonorer', meaning: 'The Dishonorer, The Humiliator, He gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem.' },
  { id: 26, arabic: 'السَّمِيعُ', transliteration: 'As-Sami', translation: 'The All-Hearing', meaning: 'The Hearer, The One who Hears all things that are heard by His Eternal Hearing without an ear, instrument or organ.' },
  { id: 27, arabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', translation: 'The All-Seeing', meaning: 'The All-Noticing, The One who Sees all things that are seen by His Eternal Seeing without a pupil or any other instrument.' },
  { id: 28, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', translation: 'The Judge', meaning: 'The Judge, He is the Ruler and His judgment is His Word.' },
  { id: 29, arabic: 'الْعَدْلُ', transliteration: 'Al-Adl', translation: 'The Just', meaning: 'The Just, The One who is entitled to do what He does.' },
  { id: 30, arabic: 'اللَّطِيفُ', transliteration: 'Al-Lateef', translation: 'The Subtle One', meaning: 'The Subtle One, The Gracious, The One who is kind to His slaves and endows upon them.' },
  { id: 31, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', translation: 'The Aware', meaning: 'The One who knows the truth of things.' },
  { id: 32, arabic: 'الْحَلِيمُ', transliteration: 'Al-Haleem', translation: 'The Forbearing', meaning: 'The Forebearing, The One who delays the punishment for those who deserve it and then He might forgive them.' },
  { id: 33, arabic: 'الْعَظِيمُ', transliteration: 'Al-Azeem', translation: 'The Great One', meaning: 'The Great One, The Mighty, The One deserving the attributes of Exaltment, Glory, Extolment, and Purity from all imperfection.' },
  { id: 34, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafoor', translation: 'The All-Forgiving', meaning: 'The Forgiving, The One who forgives a lot.' },
  { id: 35, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakoor', translation: 'The Appreciative', meaning: 'The Grateful, The One who gives a lot of reward for a little obedience.' },
  { id: 36, arabic: 'الْعَلِيُّ', transliteration: 'Al-Aliyy', translation: 'The Most High', meaning: 'The Sublime, The One who is clear from the attributes of the creatures.' },
  { id: 37, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabeer', translation: 'The Most Great', meaning: 'The Great One, The One who is greater than everything in status.' },
  { id: 38, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', translation: 'The Preserver', meaning: 'The Guardian, The Protector, The One who protects whatever and whoever He willed to protect.' },
  { id: 39, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', translation: 'The Maintainer', meaning: 'The Maintainer, The Guardian, The Feeder, The One who has the Power.' },
  { id: 40, arabic: 'الْحَسِيبُ', transliteration: 'Al-Haseeb', translation: 'The Reckoner', meaning: 'The Reckoner, The One who gives the satisfaction.' },
  { id: 41, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jaleel', translation: 'The Sublime One', meaning: 'The Sublime One, The Beneficent, The One who is attributed with greatness of Power and Glory of status.' },
  { id: 42, arabic: 'الْكَرِيمُ', transliteration: 'Al-Kareem', translation: 'The Generous One', meaning: 'The Generous One, The Bountiful, The Gracious, The One who is attributed with greatness of Power and Glory of status.' },
  { id: 43, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqeeb', translation: 'The Watcher', meaning: 'The Watcher, The One that nothing is absent from Him. Hence it\'s meaning is related to the attribute of Knowledge.' },
  { id: 44, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujeeb', translation: 'The Responsive', meaning: 'The Responsive, The One who answers the one in need if he asks Him and rescues the yearner if he calls upon Him.' },
  { id: 45, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi', translation: 'The All-Embracing', meaning: 'The Vast, The All-Embracing, The Knowledgeable.' },
  { id: 46, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakeem', translation: 'The Wise', meaning: 'The Wise, The One who is correct in His doings.' },
  { id: 47, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', translation: 'The Loving', meaning: 'The One who loves His believing slaves and His believing slaves love Him. His love to His slaves is His Will to be merciful to them and praise them.' },
  { id: 48, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majeed', translation: 'The Most Glorious', meaning: 'The Most Glorious One, The One who is with perfect Power, High Status, Compassion, Generosity and Kindness.' },
  { id: 49, arabic: 'الْبَاعِثُ', transliteration: 'Al-Ba\'ith', translation: 'The Resurrector', meaning: 'The Resurrector, The One who resurrects His slaves after death for reward and/or punishment.' },
  { id: 50, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shaheed', translation: 'The Witness', meaning: 'The Witness, The One who nothing is absent from Him.' },
  { id: 51, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', translation: 'The Truth', meaning: 'The Truth, The True, The One who truly exists.' },
  { id: 52, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakeel', translation: 'The Trustee', meaning: 'The Trustee, The One who gives the satisfaction and is relied upon.' },
  { id: 53, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', translation: 'The Strong', meaning: 'The Strong, The One with the complete Power.' },
  { id: 54, arabic: 'الْمَتِينُ', transliteration: 'Al-Mateen', translation: 'The Firm One', meaning: 'The One with extreme Power which is un-interrupted and He does not get tired.' },
  { id: 55, arabic: 'الْوَلِيُّ', transliteration: 'Al-Waliyy', translation: 'The Protecting Friend', meaning: 'The Protecting Friend, The Supporter.' },
  { id: 56, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hameed', translation: 'The Praiseworthy', meaning: 'The Praiseworthy, The praised One who deserves to be praised.' },
  { id: 57, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsee', translation: 'The Reckoner', meaning: 'The Counter, The Reckoner, The One who the count of things are known to him.' },
  { id: 58, arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi', translation: 'The Originator', meaning: 'The One who started the human being. That is, He created him.' },
  { id: 59, arabic: 'الْمُعِيدُ', transliteration: 'Al-Mu\'id', translation: 'The Restorer', meaning: 'The Reproducer, The One who brings back the creatures after death.' },
  { id: 60, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', translation: 'The Giver of Life', meaning: 'The One who took out a living human from semen that does not have a soul. He gives life by giving the souls back to the worn out bodies on the resurrection day and He makes the hearts alive by the light of knowledge.' },
  { id: 61, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumeet', translation: 'The Creator of Death', meaning: 'The One who renders the living dead.' },
  { id: 62, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', translation: 'The Living', meaning: 'The Alive, The One attributed with a life that is unlike our life and is not that of a combination of soul, flesh or blood.' },
  { id: 63, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyoom', translation: 'The Self-Subsisting', meaning: 'The One who remains and does not end.' },
  { id: 64, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', translation: 'The Perceiver', meaning: 'The Rich who is never poor. Al-Wajd is Richness.' },
  { id: 65, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', translation: 'The Illustrious', meaning: 'The Glorious, He who is Most Glorious.' },
  { id: 66, arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', translation: 'The One', meaning: 'The Unique, The One, The One without a partner.' },
  { id: 67, arabic: 'الْأَحَدُ', transliteration: 'Al-Ahad', translation: 'The Unique', meaning: 'The One.' },
  { id: 68, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', translation: 'The Eternal', meaning: 'The Eternal, The Independent, The Master who is relied upon in matters and reverted to in ones needs.' },
  { id: 69, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', translation: 'The Able', meaning: 'The Able, The Capable, The One attributed with Power.' },
  { id: 70, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', translation: 'The Powerful', meaning: 'The Powerful, The Dominant, The One with the perfect Power that nothing is withheld from Him.' },
  { id: 71, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', translation: 'The Expediter', meaning: 'The Expediter, He who brings forward whatever He wills.' },
  { id: 72, arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Mu\'akhkhir', translation: 'The Delayer', meaning: 'The Delayer, He who puts far away whatever He wills.' },
  { id: 73, arabic: 'الْأَوَّلُ', transliteration: 'Al-Awwal', translation: 'The First', meaning: 'The First, The One whose Existence is without a beginning.' },
  { id: 74, arabic: 'الْآخِرُ', transliteration: 'Al-Akhir', translation: 'The Last', meaning: 'The Last, The One whose Existence is without an end.' },
  { id: 75, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', translation: 'The Manifest', meaning: 'The Manifest, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies.' },
  { id: 76, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', translation: 'The Hidden', meaning: 'The Hidden, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies.' },
  { id: 77, arabic: 'الْوَالِي', transliteration: 'Al-Wali', translation: 'The Governor', meaning: 'The Governor, The One who owns things and manages them.' },
  { id: 78, arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta\'ali', translation: 'The Most Exalted', meaning: 'The Most Exalted, The High Exalted, The One who is clear from the attributes of the creation.' },
  { id: 79, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', translation: 'The Source of Goodness', meaning: 'The Source of All Goodness, The Righteous, The One who is kind to His creatures, who covered them with His sustenance and specified whoever He willed among them by His support, protection, and special mercy.' },
  { id: 80, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', translation: 'The Acceptor of Repentance', meaning: 'The Oft-Forgiving, The Acceptor of Repentance, The One who grants repentance to whoever He willed among His creatures and accepts his repentance.' },
  { id: 81, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', translation: 'The Avenger', meaning: 'The Avenger, The One who victoriously prevails over His enemies and punishes them for their sins. It may mean the One who destroys them.' },
  { id: 82, arabic: 'الْعَفُوُّ', transliteration: 'Al-Afuww', translation: 'The Pardoner', meaning: 'The Forgiver, The One with wide forgiveness.' },
  { id: 83, arabic: 'الرَّءُوفُ', transliteration: 'Ar-Ra\'uf', translation: 'The Compassionate', meaning: 'The Compassionate, The One with extreme Mercy. The Mercy of Allah is His will to endow upon whoever He willed among His creatures.' },
  { id: 84, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', translation: 'The Owner of All', meaning: 'The One who controls the Dominion and gives dominion to whoever He willed.' },
  { id: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Dhu-al-Jalal wa-al-Ikram', translation: 'The Lord of Majesty and Bounty', meaning: 'The One who deserves to be Exalted and not denied.' },
  { id: 86, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', translation: 'The Equitable', meaning: 'The One who is Just in His judgment.' },
  { id: 87, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami', translation: 'The Gatherer', meaning: 'The One who gathers the creatures on a day that there is no doubt about, that is the Day of Judgment.' },
  { id: 88, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghaniyy', translation: 'The Self-Sufficient', meaning: 'The One who does not need the creation.' },
  { id: 89, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', translation: 'The Enricher', meaning: 'The Enricher, The One who satisfies the necessities of the creatures.' },
  { id: 90, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani', translation: 'The Preventer', meaning: 'The Withholder.' },
  { id: 91, arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', translation: 'The Distresser', meaning: 'The One who makes harm reach to whoever He willed and benefit to whoever He willed.' },
  { id: 92, arabic: 'النَّافِعُ', transliteration: 'An-Nafi', translation: 'The Propitious', meaning: 'The One who makes harm reach to whoever He willed and benefit to whoever He willed.' },
  { id: 93, arabic: 'النُّورُ', transliteration: 'An-Nur', translation: 'The Light', meaning: 'The Light, The One who guides.' },
  { id: 94, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', translation: 'The Guide', meaning: 'The Guide, The One whom with His Guidance His believers were guided, and with His Guidance the living beings have been guided to what is beneficial for them and protected from what is harmful to them.' },
  { id: 95, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi', translation: 'The Incomparable', meaning: 'The Incomparable, The One who created the creation and formed it without any preceding example.' },
  { id: 96, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', translation: 'The Everlasting', meaning: 'The Everlasting, The One that the state of non-existence is impossible for Him.' },
  { id: 97, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', translation: 'The Inheritor', meaning: 'The Heir, The One whose Existence remains.' },
  { id: 98, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', translation: 'The Guide to Right Path', meaning: 'The Guide, The One who guides.' },
  { id: 99, arabic: 'الصَّبُورُ', transliteration: 'As-Saboor', translation: 'The Patient', meaning: 'The Patient, The One who does not quickly punish the sinners.' }
];
