export const surahList = [
    { id: 1, nameEnglish: 'Al-Fatiha', nameArabic: 'الفاتحة', meaning: 'Opening chapter' },
    { id: 2, nameEnglish: 'Al-Baqarah', nameArabic: 'البقرة', meaning: 'The Cow' },
    { id: 3, nameEnglish: 'Aal-Imran', nameArabic: 'آل عمران', meaning: 'Family of Imran' },
    { id: 4, nameEnglish: 'An-Nisa', nameArabic: 'النساء', meaning: 'The Women' },
    { id: 5, nameEnglish: "Al-Ma'idah", nameArabic: 'المائدة', meaning: 'The Table Spread' },
    { id: 6, nameEnglish: "Al-An'am", nameArabic: 'الأنعام', meaning: 'The Cattle' },
    { id: 7, nameEnglish: "Al-A'raf", nameArabic: 'الأعراف', meaning: 'The Heights' },
    { id: 8, nameEnglish: 'Al-Anfal', nameArabic: 'الأنفال', meaning: 'The Spoils of War' },
    { id: 9, nameEnglish: 'At-Tawbah', nameArabic: 'التوبة', meaning: 'Repentance / Declaration' },
    { id: 10, nameEnglish: 'Yunus', nameArabic: 'يونس', meaning: 'Prophet Jonah' },
    { id: 11, nameEnglish: 'Hud', nameArabic: 'هود', meaning: 'Prophet Hud' },
    { id: 12, nameEnglish: 'Yusuf', nameArabic: 'يوسف', meaning: 'Prophet Joseph' },
    { id: 13, nameEnglish: "Ar-Ra'd", nameArabic: 'الرعد', meaning: 'The Thunder' },
    { id: 14, nameEnglish: 'Ibrahim', nameArabic: 'إبراهيم', meaning: 'Prophet Abraham' },
    { id: 15, nameEnglish: 'Al-Hijr', nameArabic: 'الحجر', meaning: 'Rocky Tract' },
    { id: 16, nameEnglish: 'An-Nahl', nameArabic: 'النحل', meaning: 'The Bees' },
    { id: 17, nameEnglish: 'Al-Isra', nameArabic: 'الإسراء', meaning: 'Night Journey' },
    { id: 18, nameEnglish: 'Al-Kahf', nameArabic: 'الكهف', meaning: 'The Cave' },
    { id: 19, nameEnglish: 'Maryam', nameArabic: 'مريم', meaning: 'Mary' },
    { id: 20, nameEnglish: 'Ta-Ha', nameArabic: 'طه', meaning: 'Ta-Ha Chapter' },
    { id: 21, nameEnglish: 'Al-Anbiya', nameArabic: 'الأنبياء', meaning: 'The Prophets' },
    { id: 22, nameEnglish: 'Al-Hajj', nameArabic: 'الحج', meaning: 'The Pilgrimage' },
    { id: 23, nameEnglish: "Al-Mu'minun", nameArabic: 'المؤمنون', meaning: 'The Believers' },
    { id: 24, nameEnglish: 'An-Nur', nameArabic: 'النور', meaning: 'The Light' },
    { id: 25, nameEnglish: 'Al-Furqan', nameArabic: 'الفرقان', meaning: 'The Criterion' },
    { id: 26, nameEnglish: "Ash-Shu'ara", nameArabic: 'الشعراء', meaning: 'The Poets' },
    { id: 27, nameEnglish: 'An-Naml', nameArabic: 'النمل', meaning: 'The Ants' },
    { id: 28, nameEnglish: 'Al-Qasas', nameArabic: 'القصص', meaning: 'The Stories' },
    { id: 29, nameEnglish: 'Al-Ankabut', nameArabic: 'العنكبوت', meaning: 'The Spider' },
    { id: 30, nameEnglish: 'Ar-Rum', nameArabic: 'الروم', meaning: 'The Romans' },
    { id: 31, nameEnglish: 'Luqman', nameArabic: 'لقمان', meaning: 'Luqman’s Wisdom' },
    { id: 32, nameEnglish: 'As-Sajdah', nameArabic: 'السجدة', meaning: 'The Prostration' },
    { id: 33, nameEnglish: 'Al-Ahzab', nameArabic: 'الأحزاب', meaning: 'The Confederates' },
    { id: 34, nameEnglish: 'Saba', nameArabic: 'سبإ', meaning: 'People of Saba' },
    { id: 35, nameEnglish: 'Fatir', nameArabic: 'فاطر', meaning: 'The Originator' },
    { id: 36, nameEnglish: 'Ya-Sin', nameArabic: 'يس', meaning: 'Ya-Sin Chapter' },
    { id: 37, nameEnglish: 'As-Saffat', nameArabic: 'الصافات', meaning: 'The Rangers' },
    { id: 38, nameEnglish: 'Sad', nameArabic: 'ص', meaning: 'Letter Sad' },
    { id: 39, nameEnglish: 'Az-Zumar', nameArabic: 'الزمر', meaning: 'The Groups' },
    { id: 40, nameEnglish: 'Ghafir', nameArabic: 'غافر', meaning: 'The Forgiver' },
    { id: 41, nameEnglish: 'Fussilat', nameArabic: 'فصلت', meaning: 'Explained Verses' },
    { id: 42, nameEnglish: 'Ash-Shura', nameArabic: 'الشورى', meaning: 'Consultation' },
    { id: 43, nameEnglish: 'Az-Zukhruf', nameArabic: 'الزخرف', meaning: 'Ornaments of Gold' },
    { id: 44, nameEnglish: 'Ad-Dukhan', nameArabic: 'الدخان', meaning: 'The Smoke' },
    { id: 45, nameEnglish: 'Al-Jathiyah', nameArabic: 'الجاثية', meaning: 'Kneeling People' },
    { id: 46, nameEnglish: 'Al-Ahqaf', nameArabic: 'الأحقال', meaning: 'Sand Dunes Valley' },
    { id: 47, nameEnglish: 'Muhammad', nameArabic: 'محمد', meaning: 'Prophet Muhammad' },
    { id: 48, nameEnglish: 'Al-Fath', nameArabic: 'الفتح', meaning: 'The Victory' },
    { id: 49, nameEnglish: 'Al-Hujurat', nameArabic: 'الحجرات', meaning: 'The Rooms' },
    { id: 50, nameEnglish: 'Qaf', nameArabic: 'ق', meaning: 'Letter Qaf' },
    { id: 51, nameEnglish: 'Adh-Dhariyat', nameArabic: 'الذاريات', meaning: 'The Winds' },
    { id: 52, nameEnglish: 'At-Tur', nameArabic: 'الطور', meaning: 'The Mount' },
    { id: 53, nameEnglish: 'An-Najm', nameArabic: 'النجم', meaning: 'The Star' },
    { id: 54, nameEnglish: 'Al-Qamar', nameArabic: 'القمر', meaning: 'The Moon' },
    { id: 55, nameEnglish: 'Ar-Rahman', nameArabic: 'الرحمن', meaning: 'The Most Merciful' },
    { id: 56, nameEnglish: "Al-Waqi'ah", nameArabic: 'الواقعة', meaning: 'The Inevitable Event' },
    { id: 57, nameEnglish: 'Al-Hadid', nameArabic: 'الحديد', meaning: 'The Iron' },
    { id: 58, nameEnglish: 'Al-Mujadilah', nameArabic: 'المجادلة', meaning: 'The Pleading Woman' },
    { id: 59, nameEnglish: 'Al-Hashr', nameArabic: 'الحشر', meaning: 'The Gathering' },
    { id: 60, nameEnglish: 'Al-Mumtahanah', nameArabic: 'الممتحنة', meaning: 'The Tested Woman' },
    { id: 61, nameEnglish: 'As-Saff', nameArabic: 'الصف', meaning: 'The Ranks' },
    { id: 62, nameEnglish: "Al-Jumu'ah", nameArabic: 'الجمعة', meaning: 'Friday Congregation' },
    { id: 63, nameEnglish: 'Al-Munafiqun', nameArabic: 'المنافقون', meaning: 'The Hypocrites' },
    { id: 64, nameEnglish: 'At-Taghabun', nameArabic: 'التغابن', meaning: 'Loss and Gain' },
    { id: 65, nameEnglish: 'At-Talaq', nameArabic: 'الطلاق', meaning: 'Divorce Laws' },
    { id: 66, nameEnglish: 'At-Tahrim', nameArabic: 'التحريم', meaning: 'The Prohibition' },
    { id: 67, nameEnglish: 'Al-Mulk', nameArabic: 'الملك', meaning: 'The Kingdom' },
    { id: 68, nameEnglish: 'Al-Qalam', nameArabic: 'القلم', meaning: 'The Pen' },
    { id: 69, nameEnglish: 'Al-Haqqah', nameArabic: 'الحاقة', meaning: 'The Reality' },
    { id: 70, nameEnglish: "Al-Ma'arij", nameArabic: 'المعارج', meaning: 'Ascending Steps' },
    { id: 71, nameEnglish: 'Nuh', nameArabic: 'نوح', meaning: 'Prophet Noah' },
    { id: 72, nameEnglish: 'Al-Jinn', nameArabic: 'الجن', meaning: 'The Jinn' },
    { id: 73, nameEnglish: 'Al-Muzzammil', nameArabic: 'المزمل', meaning: 'The Wrapped One' },
    { id: 74, nameEnglish: 'Al-Muddathir', nameArabic: 'المدثر', meaning: 'The Covered One' },
    { id: 75, nameEnglish: 'Al-Qiyamah', nameArabic: 'القيامة', meaning: 'The Resurrection' },
    { id: 76, nameEnglish: 'Al-Insan', nameArabic: 'الإنسان', meaning: 'The Human' },
    { id: 77, nameEnglish: 'Al-Mursalat', nameArabic: 'المرسلات', meaning: 'The Messengers' },
    { id: 78, nameEnglish: 'An-Naba', nameArabic: 'النبأ', meaning: 'The Great News' },
    { id: 79, nameEnglish: "An-Nazi'at", nameArabic: 'النازعات', meaning: 'Those Who Pull' },
    { id: 80, nameEnglish: 'Abasa', nameArabic: 'عبس', meaning: 'He Frowned' },
    { id: 81, nameEnglish: 'At-Takwir', nameArabic: 'التكوير', meaning: 'Folding of the Sun' },
    { id: 82, nameEnglish: 'Al-Infitar', nameArabic: 'الإنفطار', meaning: 'The Splitting' },
    { id: 83, nameEnglish: 'Al-Mutaffifin', nameArabic: 'المطففين', meaning: 'The Cheaters' },
    { id: 84, nameEnglish: 'Al-Inshiqaq', nameArabic: 'الإنشقاق', meaning: 'The Split Sky' },
    { id: 85, nameEnglish: 'Al-Buruj', nameArabic: 'البروج', meaning: 'The Constellations' },
    { id: 86, nameEnglish: 'At-Tariq', nameArabic: 'الطارق', meaning: 'The Night Star' },
    { id: 87, nameEnglish: "Al-A'la", nameArabic: 'الأعلى', meaning: 'The Most High' },
    { id: 88, nameEnglish: 'Al-Ghashiyah', nameArabic: 'الغاشية', meaning: 'The Overwhelming' },
    { id: 89, nameEnglish: 'Al-Fajr', nameArabic: 'الفجر', meaning: 'The Dawn' },
    { id: 90, nameEnglish: 'Al-Balad', nameArabic: 'البلد', meaning: 'The City' },
    { id: 91, nameEnglish: 'Ash-Shams', nameArabic: 'الشمس', meaning: 'The Sun' },
    { id: 92, nameEnglish: 'Al-Layl', nameArabic: 'الليل', meaning: 'The Night' },
    { id: 93, nameEnglish: 'Ad-Duha', nameArabic: 'الضحى', meaning: 'The Morning Light' },
    { id: 94, nameEnglish: 'Ash-Sharh', nameArabic: 'الشرح', meaning: 'The Relief' },
    { id: 95, nameEnglish: 'At-Tin', nameArabic: 'التين', meaning: 'The Fig' },
    { id: 96, nameEnglish: 'Al-Alaq', nameArabic: 'العلق', meaning: 'The Clot' },
    { id: 97, nameEnglish: 'Al-Qadr', nameArabic: 'القدر', meaning: 'Night of Power' },
    { id: 98, nameEnglish: 'Al-Bayyinah', nameArabic: 'البينة', meaning: 'The Clear Proof' },
    { id: 99, nameEnglish: 'Az-Zalzalah', nameArabic: 'الزلزلة', meaning: 'The Earthquake' },
    { id: 100, nameEnglish: 'Al-Adiyat', nameArabic: 'العاديات', meaning: 'Racing Horses' },
    { id: 101, nameEnglish: "Al-Qari'ah", nameArabic: 'القارعة', meaning: 'The Calamity' },
    { id: 102, nameEnglish: 'At-Takathur', nameArabic: 'التكاثر', meaning: 'Piling Up Wealth' },
    { id: 103, nameEnglish: 'Al-Asr', nameArabic: 'العصر', meaning: 'The Time' },
    { id: 104, nameEnglish: 'Al-Humazah', nameArabic: 'الهمزة', meaning: 'The Slanderer' },
    { id: 105, nameEnglish: 'Al-Fil', nameArabic: 'الفيل', meaning: 'The Elephant' },
    { id: 106, nameEnglish: 'Quraysh', nameArabic: 'قريش', meaning: 'Quraysh Tribe' },
    { id: 107, nameEnglish: "Al-Ma'un", nameArabic: 'الماعون', meaning: 'Small Kindness' },
    { id: 108, nameEnglish: 'Al-Kawthar', nameArabic: 'الكوثر', meaning: 'Abundant Blessing' },
    { id: 109, nameEnglish: 'Al-Kafirun', nameArabic: 'الكافرون', meaning: 'The Disbelievers' },
    { id: 110, nameEnglish: 'An-Nasr', nameArabic: 'النصر', meaning: 'Divine Help and Victory' },
    { id: 111, nameEnglish: 'Al-Masad', nameArabic: 'المسد', meaning: 'Palm Fiber / Flame Carrier' },
    { id: 112, nameEnglish: 'Al-Ikhlas', nameArabic: 'الإخلاص', meaning: 'Pure Monotheism' },
    { id: 113, nameEnglish: 'Al-Falaq', nameArabic: 'الفلق', meaning: 'Daybreak' },
    { id: 114, nameEnglish: 'An-Nas', nameArabic: 'الناس', meaning: 'Mankind' },
];
